apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
      - containerPort: 80
    lifecycle:
        postStart:
          exec:
            command: ['sh', '-c', 'echo "2" > /usr/share/nginx/html/index.html']