apiVersion: v1
kind: Service
metadata:
  name: my-service-2
  namespace: node-port
spec:
  type: NodePort
  selector:
    app: my-app-2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007